### ISSUE TITLE
안드로이드 로그인 처리후 앱 꺼짐 현상

### ISSUE THREAD

**Issue by Wanderlust-sol** [react-native-seoul/react-native-kakao-login#194]
### Version of kakao-login libraries
v3.0.1

### Version of react-native
v0.63.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
로그인 성공 후 앱 정상 작동

### Actual behavior
로그인 후 앱이 중단되며 꺼지는 현상

### Tested environment (Emulator? Real Device?)
갤럭시 s8

**Comment by hyochan** [comment]
@Wanderlust-sol 안드로이드에서 logcat에서 오류난 부분을 찾아서 공유해주시면 대단히 감사하겠습니다 🙏

**Comment by Wanderlust-sol** [comment]
실행해보았는데 
login() 메서드후 앱은 잘작동되는데 곧바로 getProfile() 메서드를 작동시키니 아래와 같은 오류가 발생했습니다.
```javascript
const onPressKakao = async (): Promise<void> => {
    const token: KakaoOAuthToken = await login();
    console.log('token', token);
    const profile: KakaoProfile = await getProfile();
    console.log(profile);
  };
```

```
2021-03-24 18:08:01.987 3757-3757/com.xinapse.malmoy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xinapse.malmoy, PID: 3757
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.kakao.sdk.user.model.Profile.getNickname()' on a null object reference
        at com.dooboolab.kakaologins.RNKakaoLoginsModule.lambda$getProfile$5$RNKakaoLoginsModule(RNKakaoLoginsModule.java:159)
        at com.dooboolab.kakaologins.-$$Lambda$RNKakaoLoginsModule$RIoCgFwaf7ycavvkFa2W7ouDL7w.invoke(Unknown Source:8)
        at com.kakao.sdk.user.UserApiClient$me$1.onComplete(UserApiClient.kt:161)
        at com.kakao.sdk.user.UserApiClient$me$1.onComplete(UserApiClient.kt:159)
        at com.kakao.sdk.network.ApiCallback.onResponse(ApiCallback.kt:43)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by hyochan** [comment]
이슈 리포트 감사합니다. 수정 사항은 [3.0.2](https://github.com/react-native-seoul/react-native-kakao-login/releases/tag/3.0.2) 에 반영 되었습니다. 계속 문제가 발생하면 이슈보드를 새로 생성해주세요 🙏
